{{$parent := $}}
{{- with .Values.imagePullSecret }}
{{- with .create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "moondog-navigator.imagePullSecretName" $parent }}
  namespace: {{ $.Release.Namespace }}
data:
  .dockerconfigjson: {{ . | toJson | b64enc }}
{{- end -}}
{{- end -}}
