{{- if .Values.imageCredentials -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "moondog-navigator.imagePullSecretName" . }}
  namespace: {{ $.Release.Namespace }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
