apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "moondog-navigator.envSecretName" . }}
  namespace: {{ $.Release.Namespace }}
data:
  SECRET_KEY_BASE: {{ 64 | randAlphaNum | b64enc }}
  {{- range .Values.clusters -}}
  {{ $clusterName := (.name | upper) }}
  CLUSTERCONFIG_{{ $clusterName }}_DEX_CLIENT_SECRET: {{ .oidc.clientSecret | b64enc }}
  {{- end -}}
