{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "moondog-navigator.serviceAccountName" . }}
  labels:
{{ include "moondog-navigator.labels" . | indent 4 }}
{{- end -}}
