{{ $roleDefinitions := .Values.roleDefinitions }}

{{- with .Values.bindings.cluster }}
  {{ $allRoleNames := list }}

  {{- range $section := list .groups .users }}
    {{- range $_, $roleNames := $section }}
      {{ $allRoleNames = concat $allRoleNames $roleNames }}
    {{- end }}
  {{- end }}

  {{- range $roleName := uniq $allRoleNames }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $roleName | quote }}
rules: {{ get $roleDefinitions $roleName | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
