{{ $top := . }}

{{- range $roleName, $_ := .Values.roleDefinitions }}
  {{ $groups := list }}
  {{ $users := list }}

  {{- with $top.Values.bindings.cluster }}
    {{- range $subject, $roleNames := .groups }}
      {{- if has $roleName $roleNames }}
        {{ $groups = append $groups $subject }}
      {{- end }}
    {{- end }}
    {{- range $subject, $roleNames := .users }}
      {{- if has $roleName $roleNames }}
        {{ $users = append $users $subject }}
      {{- end }}
    {{- end }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $roleName | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $roleName | quote }}
subjects:
  {{- range $groups }}
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: {{ . | quote }}
  {{- end }}
  {{- range $users }}
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ . | quote }}
  {{- end }}

{{- end }}
