# Define the names and rules for the
# ClusterRoles and Roles to be created.
#
# EXAMPLE
#
# =================
#
# roleDefinitions:
#   my-admin-role-name:
#
#     # The definition follows the format of the `rules` section
#     # of a ClusterRoleBinding or RoleBinding as documented
#     # here: https://kubernetes.io/docs/reference/access-authn-authz/rbac/
#
#     - apiGroups:
#       - '*'
#     resources:
#       - '*'
#     verbs:
#       - '*'
#   - nonResourceURLs:
#       - '*'
#     verbs:
#       - '*'

roleDefinitions: {}

# The chart will only create the
# Roles and ClusterRoles that have bindings.
#
# Create 1 entry per user or group.
# Set namespace to "*" for ClusterRole access,
# or set it to a namespace name for Role access.
#
# EXAMPLE
#
# =================
#
# bindings:
#   - group: administrators
#     bindTo:
#       - namespace: '*'
#         roles:
#           - read-write-all
#   - user: root
#     bindTo:
#       - namespace: '*'
#         roles:
#           - read-write-all
#   - group: engineers
#     bindTo:
#       - namespace: '*'
#         roles:
#           - another-role
#           - yet-another-role
#   - group: demo-guests
#     bindTo:
#       - namespace: demo
#         roles:
#           - read-all-except-secrets
#   - user: alice
#     bindTo:
#       - namespace: '*'
#         roles:
#           - read-all-except-secrets
#       - namespace: another-namespace
#         roles:
#           - another-role
#           - yet-another-role
#       - namespace: demo
#         roles:
#           - read-write-all

bindings: []
